In [1]:
import pandas as pd

df = pd.read_csv('Offenses_by_Agency_Table_data_WI_2018data.csv')
df2=pd.read_csv('Offenses_by_Agency_Table_data_WI_2019data.csv')
df4=pd.read_csv('Offenses_by_Agency_Table_data_WI_2020data.csv')

df2.head()

,County,Agency Name,Offense Description,Min. year of year,Offense Count
0,Adams,Rome Town PD,Human Trafficking - Involuntary Servitude,2019,0
1,Adams,Adams PD,Human Trafficking - Involuntary Servitude,2019,0
2,Adams,Adams Co SO,Human Trafficking - Involuntary Servitude,2019,0
3,Adams,Rome Town PD,Human Trafficking - Commercial Sex,2019,0
4,Adams,Adams PD,Human Trafficking - Commercial Sex,2019,0

In [2]:
df3=pd.merge(df,df2,on=['Agency Name','Offense Description'])
df3.head(25)

,State,County_x,Agency Name,Offense Description,Min. year of year_x,Offense Count_x,County_y,Min. year of year_y,Offense Count_y
0,WI,Adams,Rome Town PD,Simple Assault,2018,11,Adams,2019,8
1,WI,Adams,Adams PD,Simple Assault,2018,2,Adams,2019,7
2,WI,Adams,Adams Co SO,Simple Assault,2018,130,Adams,2019,131
3,WI,Adams,Rome Town PD,Arson,2018,1,Adams,2019,0
4,WI,Adams,Adams PD,Arson,2018,1,Adams,2019,1
5,WI,Adams,Adams Co SO,Arson,2018,1,Adams,2019,2
6,WI,Adams,Rome Town PD,Motor Vehicle Theft,2018,0,Adams,2019,1
7,WI,Adams,Adams PD,Motor Vehicle Theft,2018,2,Adams,2019,3
8,WI,Adams,Adams Co SO,Motor Vehicle Theft,2018,8,Adams,2019,12
9,WI,Adams,Rome Town PD,Larceny Theft,2018,6,Adams,2019,17
10,WI,Adams,Adams PD,Larceny Theft,2018,69,Adams,2019,60
11,WI,Adams,Adams Co SO,Larceny Theft,2018,85,Adams,2019,134
12,WI,Adams,Rome Town PD,Burglary,2018,0,Adams,2019,6
13,WI,Adams,Adams PD,Burglary,2018,6,Adams,2019,4
14,WI,Adams,Adams Co SO,Burglary,2018,94,Adams,2019,109
15,WI,Adams,Rome Town PD,Aggravated Assault,2018,3,Adams,2019,0
16,WI,Adams,Adams PD,Aggravated Assault,2018,2,Adams,2019,2
17,WI,Adams,Adams Co SO,Aggravated Assault,2018,26,Adams,2019,21
18,WI,Adams,Rome Town PD,Robbery,2018,0,Adams,2019,0
19,WI,Adams,Adams PD,Robbery,2018,1,Adams,2019,1
20,WI,Adams,Adams Co SO,Robbery,2018,1,Adams,2019,0
21,WI,Adams,Rome Town PD,Rape - revised 2017,2018,0,Adams,2019,4
22,WI,Adams,Adams PD,Rape - revised 2017,2018,4,Adams,2019,6
23,WI,Adams,Adams Co SO,Rape - revised 2017,2018,0,Adams,2019,0
24,WI,Adams,Rome Town PD,Homicide,2018,0,Adams,2019,0

In [3]:
df5=pd.merge(df3,df4,on=['Agency Name','Offense Description'])
df5.head(25)

,State,County_x,Agency Name,Offense Description,Min. year of year_x,Offense Count_x,County_y,Min. year of year_y,Offense Count_y,County,Min. year of year,Offense Count
0,WI,Adams,Rome Town PD,Simple Assault,2018,11,Adams,2019,8,Adams,2020,6
1,WI,Adams,Adams PD,Simple Assault,2018,2,Adams,2019,7,Adams,2020,11
2,WI,Adams,Adams Co SO,Simple Assault,2018,130,Adams,2019,131,Adams,2020,147
3,WI,Adams,Rome Town PD,Arson,2018,1,Adams,2019,0,Adams,2020,0
4,WI,Adams,Adams PD,Arson,2018,1,Adams,2019,1,Adams,2020,0
5,WI,Adams,Adams Co SO,Arson,2018,1,Adams,2019,2,Adams,2020,0
6,WI,Adams,Rome Town PD,Motor Vehicle Theft,2018,0,Adams,2019,1,Adams,2020,0
7,WI,Adams,Adams PD,Motor Vehicle Theft,2018,2,Adams,2019,3,Adams,2020,0
8,WI,Adams,Adams Co SO,Motor Vehicle Theft,2018,8,Adams,2019,12,Adams,2020,7
9,WI,Adams,Rome Town PD,Larceny Theft,2018,6,Adams,2019,17,Adams,2020,15
10,WI,Adams,Adams PD,Larceny Theft,2018,69,Adams,2019,60,Adams,2020,33
11,WI,Adams,Adams Co SO,Larceny Theft,2018,85,Adams,2019,134,Adams,2020,140
12,WI,Adams,Rome Town PD,Burglary,2018,0,Adams,2019,6,Adams,2020,12
13,WI,Adams,Adams PD,Burglary,2018,6,Adams,2019,4,Adams,2020,2
14,WI,Adams,Adams Co SO,Burglary,2018,94,Adams,2019,109,Adams,2020,110
15,WI,Adams,Rome Town PD,Aggravated Assault,2018,3,Adams,2019,0,Adams,2020,1
16,WI,Adams,Adams PD,Aggravated Assault,2018,2,Adams,2019,2,Adams,2020,3
17,WI,Adams,Adams Co SO,Aggravated Assault,2018,26,Adams,2019,21,Adams,2020,34
18,WI,Adams,Rome Town PD,Robbery,2018,0,Adams,2019,0,Adams,2020,0
19,WI,Adams,Adams PD,Robbery,2018,1,Adams,2019,1,Adams,2020,0
20,WI,Adams,Adams Co SO,Robbery,2018,1,Adams,2019,0,Adams,2020,1
21,WI,Adams,Rome Town PD,Rape - revised 2017,2018,0,Adams,2019,4,Adams,2020,2
22,WI,Adams,Adams PD,Rape - revised 2017,2018,4,Adams,2019,6,Adams,2020,4
23,WI,Adams,Adams Co SO,Rape - revised 2017,2018,0,Adams,2019,0,Adams,2020,0
24,WI,Adams,Rome Town PD,Homicide,2018,0,Adams,2019,0,Adams,2020,0

In [4]:
df5.to_csv('2018_2019_2020.csv')

In [1]:
import pandas as pd

df6 = pd.read_csv('alcohol_consumption.csv')
df6.head(10)

,State,County,Both_Sexes_2002,Females_2002,Males_2002,Both_Sexes_2003,Females_2003,Males_2003,Both_Sexes_2004,Females_2004,...,Males_2011,Both_Sexes_2012,Females_2012,Males_2012,Percent_Change_2002_2012_Both_Sexes,Percent_Change_2002_2012_Females,Percent_Change_2002_2012_Males,Percent_Change_2005_2012_Both_Sexes,Percent_Change_2005_2012_Females,Percent_Change_2005_2012_Males
0,Wisconsin,Adams,59.8,55.0,64.8,61.5,56.5,66.6,60.0,55.4,...,65.1,60.3,57.9,62.8,0.9,5.3,-3.0,-0.8,2.1,-3.4
1,Wisconsin,Ashland,65.5,58.2,73.1,67.5,60.3,74.8,65.0,57.9,...,73.8,65.2,59.5,71.0,-0.6,2.3,-2.9,-1.5,-0.1,-2.7
2,Wisconsin,Barron,64.6,56.7,72.7,65.5,57.9,73.3,63.7,56.5,...,71.5,62.7,57.3,68.3,-2.9,1.0,-6.1,-2.2,0.2,-4.2
3,Wisconsin,Bayfield,69.6,63.4,76.0,70.8,64.5,77.3,69.4,63.2,...,77.6,68.1,62.0,74.4,-2.2,-2.2,-2.2,-2.1,-2.4,-1.8
4,Wisconsin,Brown,74.1,67.9,80.4,74.4,68.5,80.5,72.9,67.3,...,76.6,70.1,66.2,74.1,-5.4,-2.5,-7.9,-4.7,-3.2,-6.1
5,Wisconsin,Buffalo,67.7,60.4,75.3,67.4,60.0,75.1,66.7,59.6,...,74.6,67.1,62.2,72.2,-0.9,3.0,-4.1,-0.4,2.4,-2.8
6,Wisconsin,Burnett,65.6,59.7,71.6,66.6,60.6,72.8,64.4,58.4,...,73.6,64.4,58.2,70.9,-1.7,-2.5,-1.0,-0.6,-1.4,0.1
7,Wisconsin,Calumet,72.8,66.3,79.6,73.6,67.3,80.2,72.8,66.7,...,79.0,71.9,67.0,77.0,-1.3,1.0,-3.3,-1.9,-0.7,-3.0
8,Wisconsin,Chippewa,70.0,62.6,77.6,70.9,63.7,78.3,69.3,62.4,...,77.4,69.9,64.9,75.0,-0.1,3.7,-3.3,-0.2,2.1,-2.2
9,Wisconsin,Clark,62.3,53.1,71.9,63.7,54.8,72.8,62.0,53.5,...,68.9,61.6,57.0,66.5,-1.1,7.4,-7.5,-1.4,4.3,-6.0